export const INIT_SERVERS = 'INIT_SERVERS';
export const ADD_SERVER = 'ADD_SERVER';
export const REMOVE_SERVER = 'REMOVE_SERVER';

export const SHOW_ADD_SERVER_MODAL = 'SHOW_ADD_SERVER_MODAL';
export const HIDE_ADD_SERVER_MODAL = 'HIDE_ADD_SERVER_MODAL';

export const SHOW_REMOVE_SERVER_MODAL = 'SHOW_REMOVE_SERVER_MODAL';
export const HIDE_REMOVE_SERVER_MODAL = 'HIDE_REMOVE_SERVER_MODAL';

export const SHOW_SEARCH_JOB_MODAL = 'SHOW_SEARCH_JOB_MODAL';
export const HIDE_SEARCH_JOB_MODAL = 'HIDE_SEARCH_JOB_MODAL';

export const SHOW_ADD_JOB_MODAL = 'SHOW_ADD_JOB_MODAL';
export const HIDE_ADD_JOB_MODAL = 'HIDE_ADD_JOB_MODAL';

export const IS_BUSY = 'IS_BUSY';
export const NOT_BUSY = 'NOT_BUSY';

export const SET_SERVER = 'SET_SERVER';
export const UNSET_SERVER = 'UNSET_SERVER';

export const START_AUTO_UPDATE = 'START_AUTO_UPDATE';
export const STOP_AUTO_UPDATE = 'STOP_AUTO_UPDATE';
export const TOGGLE_AUTO_UPDATE = 'TOGGLE_AUTO_UPDATE';